### ISSUE TITLE
[Bug] Doesn't automatically scroll when editing text

### ISSUE THREAD

**Issue by MrIkso** [Rosemoe/CodeEditor#10] opened 2020-08-11 08:02 UTC
A bug was found when you type text, then when adding new lines, it does not automatically spliced ​​down, for the visibility of the input, also if there is a long text, it is also strange to spliced ​​text to the left

**Comment by Rosemoe** [comment] 2020-08-11 08:34
It did not scroll automatically because the sample application's manifest did not add a flag to re-layout when the input method is shown.
So when the input method is in screen, editor's size is not changed and when you can not see the characters, they actually are still in the editor's considered visible area.
Add 
***android:windowSoftInputMode="adjustResize"***
to the editor's activity will solve the problem.

And the issue about long text's visibility is really a bug, I'll fix it soon.
Thanks for your feedback.

**Comment by MrIkso** [comment] 2020-08-11 11:36
@Rosemoe 

> android:windowSoftInputMode="adjustResize"


Work, but edittext layout blinking, when keyboard shows and hides. Maybe you use this idea?
https://github.com/MrIkso/CodeEditor/blob/master/codeeditor/src/main/java/com/mrikso/codeeditor/view/FreeScrollingTextField.java#L1289

**Comment by Rosemoe** [comment] 2020-08-11 14:35
I do not really understand what is 'blinking'.
This attribute works well on my device.
Could you please give a little description or gif to help me know it better?

I'll view the code in your link.

**Comment by MrIkso** [comment] 2020-08-11 16:16
Video
https://drive.google.com/file/d/1Dp8Hpy8L7cw6LBf-z5jUD7--mZ5NeiWo/view?usp=drivesdk
this will be clearly visible with a dark theme in the editor.

**Comment by Rosemoe** [comment] 2020-08-12 02:09
It seems to be caused by the system policy.
When the input method is still in animation, the layout of activity has already been resized.
I can not solve this in editor.
You may apply a dark theme to the activity and editor to cover this.

**Comment by MrIkso** [comment] 2020-08-12 13:47
> I can not solve this in editor.
@Rosemoe  that's why I propose to do everything by auto-scrolling in the code, as in the example above

**Comment by Rosemoe** [comment] 2020-08-13 02:12
There is a similar method in method as well.
And when the 'drop' in your editor is not shown, they have the same ability. And it is called each time the text/selection changes to make the right selection visible.
Padding is not supported in my editor now, so it is safe to use getHeight/getWidth directly.
That's why I can not find where the problem is.
https://github.com/Rosemoe/CodeEditor/blob/c0c9e1e62f80bbd4ca9ad169618ad50319e6618d/editor/src/main/java/io/github/rosemoe/editor/widget/CodeEditor.java#L1750

**Comment by Rosemoe** [comment] 2020-08-13 07:21
I have observed some other editors such as AIDE's and MT Manager's.
They are getting the same problem as mine.
If I open the switch to make animations 4x longer, it is very obvious.
At the beginning of a input method's entrace or exit, the layout is resized.
I do not know what is the situation in your editor because I can not get my computer to compile a project with androidx.
And mobile QQ's policy is interesting, it has a delay until the layout resize. But this can not solve the problem from the source and it is not very easy to do the delay because usually we have to use onSizeChanged() to know whether the keyboard is shown. If ***adjustPan*** is applied to the window, the size will not be changed and onSizeChanged() will not be called. If ***adjustResize*** is applied to the window, we will have to recover the size of layout on the first time onSizeChanged() has a smaller height than before. But that will cause onSizeChanged() to be called again and we do not whether it is caused by the keyboard.
It also has the problem that this can not adaptes to various input method applications and if a user choose to disable the animation, the delay can be annoying.

**Comment by Rosemoe** [comment] 2020-08-13 07:28
Now I have viewed another editor modified from text warrior. It also has the problem.

**Comment by TimScriptov** [comment] 2020-08-13 11:53
@Rosemoe
In Aide bad Code editor.

In MT Manager cool Code editor

**Comment by Rosemoe** [comment] 2020-08-13 14:31
@TimScriptov 
> In Aide bad Code editor.
> 
> In MT Manager cool Code editor

Yes, I agree with you.
MT Manager's editor is quite smooth.

**Comment by Rosemoe** [comment] 2020-08-14 12:24
The layout flash problem will not be fixed in editor's code. Users may solve it by themselves.

**Closed by Rosemoe** 2020-08-14 12:24 UTC
Labels: bug
